### ISSUE TITLE
NPE on retrieving card stock [Postgresql]

### ISSUE THREAD

**Issue by muff1nman** [nicho92/MtgDesktopCompanion#11]
Ran into the following after creating new stock. Looks like npe was on editions column handling..?
```
Exception in thread "reload stock" java.lang.NullPointerException
	at org.magic.gui.models.CardStockTableModel.getValueAt(CardStockTableModel.java:112)
	at net.coderazzi.filters.gui.ChoicesHandler$RowEntry.getValue(ChoicesHandler.java:186)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport$EditorHandle.handleRow(AdaptiveChoicesHandler.java:637)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.iterateRows(AdaptiveChoicesHandler.java:457)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.extractChoices(AdaptiveChoicesHandler.java:441)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.rowsAdded(AdaptiveChoicesHandler.java:269)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.tableChanged(AdaptiveChoicesHandler.java:243)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler.tableUpdated(AdaptiveChoicesHandler.java:137)
	at net.coderazzi.filters.gui.ChoicesHandler.tableChanged(ChoicesHandler.java:108)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableDataChanged(AbstractTableModel.java:198)
	at org.magic.gui.models.CardStockTableModel.init(CardStockTableModel.java:47)
	at org.magic.gui.StockPanelGUI$8$1.run(StockPanelGUI.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Reproduce steps are: 
1. Add card to library
2. Under collection, use the stock panel to add 4 new stock
3. Go to the stock tab - Nothing shows up
4. Click refresh - Exception occurs

**Comment by nicho92** [comment]
Missing 'mcard' field in insert query saveOrUpdateStock
