### ISSUE TITLE
getting compilation issues

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#112]
cannot run program, getting compilation error after last pull

Exception in thread "AWT-EventQueue-0" java.lang.Error: Unresolved compilation problem: 

	at org.magic.gui.components.CardSearchPanel.getInstance(CardSearchPanel.java:134)
	at org.magic.gui.MagicGUI.initGUI(MagicGUI.java:228)
	at org.magic.gui.MagicGUI.<init>(MagicGUI.java:75)
	at org.magic.api.main.MtgDesktopCompanion.lambda$0(MtgDesktopCompanion.java:65)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by nicho92** [comment]
not enough details. can you run project/clean from eclipse and rerun a build ?

**Comment by Brolmeel** [comment]
tried cleanup source , same issue
deleted project and did a clean pull from github, same issue

**Comment by nicho92** [comment]
can you run it from eclipse ?

**Comment by Brolmeel** [comment]
No running from Eclipse gives me the compile error

![image](https://user-images.githubusercontent.com/21075655/79505887-625b6400-8035-11ea-9f23-963a5e6e6b18.png)

**Comment by Brolmeel** [comment]
I switched to JavaSE-13 and now it runs.
Thanks
