### ISSUE TITLE
issue cardmarketpricer

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#131]
not showing prices anymore

2020-08-22 11:54:38 ERROR org.magic.api.pricers.impl.MagicCardMarketPricer2 198  - Error retrieving prices for Armada Wurm
com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.StaxReader.pullNextEvent(StaxReader.java:73)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)
	at com.thoughtworks.xstream.io.xml.StaxReader.<init>(StaxReader.java:45)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createStaxReader(StaxDriver.java:173)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createReader(StaxDriver.java:92)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1338)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1329)
	at org.api.mkm.services.ProductServices.findProduct(ProductServices.java:128)
	at org.magic.api.pricers.impl.MagicCardMarketPricer2.getLocalePrice(MagicCardMarketPricer2.java:155)
	at org.magic.api.interfaces.abstracts.AbstractMagicPricesProvider.getPrice(AbstractMagicPricesProvider.java:25)
	at org.magic.gui.components.PricesTablePanel$3.doInBackground(PricesTablePanel.java:143)
	at org.magic.gui.components.PricesTablePanel$3.doInBackground(PricesTablePanel.java:1)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
	at com.thoughtworks.xstream.io.xml.StaxReader.pullNextEvent(StaxReader.java:58)
	... 20 more

**Comment by Brolmeel** [comment]
yes that works
