### ISSUE TITLE
Issue MagicCardMarket export

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#134]
2020-09-01 16:59:38 ERROR org.magic.services.MTGControler 367  - error
org.api.mkm.exceptions.MkmNetworkException: 400:Bad Request,Whenever something goes wrong with your request, e.g. your POST data and/or structure is wrong, or you want to access an article in your stock by providing an invalid ArticleID, a 400 Bad Request HTTP status is returned, describing the error within the content.
	at org.api.mkm.tools.Tools.getXMLResponse(Tools.java:126)
	at org.api.mkm.services.WantsService.addItem(WantsService.java:159)
	at org.magic.api.exports.impl.MkmOnlineExport.exportDeck(MkmOnlineExport.java:205)
	at org.magic.services.workers.CardExportWorker.doInBackground(CardExportWorker.java:52)
	at org.magic.services.workers.CardExportWorker.doInBackground(CardExportWorker.java:20)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by Brolmeel** [comment]
example deck that fails
[EDHREC_Arcane_Maelstrom_Upgrade.json.txt](https://github.com/nicho92/MtgDesktopCompanion/files/5157134/EDHREC_Arcane_Maelstrom_Upgrade.json.txt)
