### ISSUE TITLE
error when trying to start Web UI Server in linux

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#136]
![image](https://user-images.githubusercontent.com/70637347/93212573-0c652680-f763-11ea-906e-b7ed047e53fb.png)

I tried playing with serverport in  Servers-config, but keep getting above error

**Comment by nicho92** [comment]
can you try to run apps with root ? and let me know ?

**Comment by Thorgal-The-Viking** [comment]
running as root gives me 


Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':10.0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:99)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:58)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
        at java.desktop/java.awt.Window.initGC(Window.java:477)
        at java.desktop/java.awt.Window.init(Window.java:497)
        at java.desktop/java.awt.Window.<init>(Window.java:539)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
        at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
        at java.desktop/javax.swing.JWindow.<init>(JWindow.java:183)
        at java.desktop/javax.swing.JWindow.<init>(JWindow.java:135)
        at org.magic.gui.components.dialog.MTGSplashScreen.<init>(MTGSplashScreen.java:30)
        at org.magic.api.main.MtgDesktopCompanion.<init>(MtgDesktopCompanion.java:36)
        at org.magic.api.main.MtgDesktopCompanion.main(MtgDesktopCompanion.java:30)

**Comment by nicho92** [comment]
Standard linux user can't open ports below 1024. Try to put 1025 then go to http://localhost:1025.

**Comment by nicho92** [comment]
maybe you should restart app

**Comment by Thorgal-The-Viking** [comment]
that worked. Thanks!

**Comment by nyteghost** [comment]
Where is Servers-config?
