### ISSUE TITLE
error exporting to MKM

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#149]
2021-01-08 23:33:33 DEBUG org.magic.api.exports.impl.MkmOnlineExport 206  - Create null list with 1 items
2021-01-08 23:33:33 ERROR org.magic.services.workers.CardExportWorker 66  - error export with MagicCardMarket
org.api.mkm.exceptions.MkmNetworkException: 400:Bad Request,Whenever something goes wrong with your request, e.g. your POST data and/or structure is wrong, or you want to access an article in your stock by providing an invalid ArticleID, a 400 Bad Request HTTP status is returned, describing the error within the content.
	at org.api.mkm.tools.Tools.getXMLResponse(Tools.java:126)
	at org.api.mkm.services.WantsService.addItem(WantsService.java:159)
	at org.magic.api.exports.impl.MkmOnlineExport.exportDeck(MkmOnlineExport.java:207)
	at org.magic.services.workers.CardExportWorker.doInBackground(CardExportWorker.java:63)
	at org.magic.services.workers.CardExportWorker.doInBackground(CardExportWorker.java:20)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by nicho92** [comment]
Can you tell me which item you want to export ?

**Comment by Thorgal-The-Viking** [comment]
trying to export deck to MKM

**Comment by nicho92** [comment]
can you export it with Json export and join it to this issue ?

**Comment by Thorgal-The-Viking** [comment]
uploaded json export

[TEST-EXP.json.txt](https://github.com/nicho92/MtgDesktopCompanion/files/5795072/TEST-EXP.json.txt)

**Comment by nicho92** [comment]
Thanks. I think there is an update or a bug on wantlists mkm api .. i tried with there samples, i've same error. 
I keep you posted

**Comment by Thorgal-The-Viking** [comment]
were you able to check this yet? I find this very usefull to be able to export to MKM to buy cards

**Comment by nicho92** [comment]
Bug found -_- ...they changed one Uppercase letter........

**Comment by Thorgal-The-Viking** [comment]
great work!

**Comment by Thorgal-The-Viking** [comment]
got this build error

[ERROR] Failed to execute goal on project magic-api: Could not resolve dependencies for project org.magic:magic-api:jar:2.22: Failure to find com.github.nicho92:mkm-api-java:jar:0.11.2 in https://repo.panda-lang.org/ was cached in the local repository, resolution will not be reattempted until the update interval of panda-repository has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by nicho92** [comment]
i think it's good, repository wasn't updated
