### ISSUE TITLE
Deck Tag not working

### ISSUE THREAD

**Issue by JulienSambre** [nicho92/MtgDesktopCompanion#179]
Hi!

I tried to add a tag to a deck and I got the following stack : 

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException
        at java.base/java.util.AbstractList.add(Unknown Source)
        at java.base/java.util.AbstractList.add(Unknown Source)
        at org.magic.gui.components.editor.JTagsPanel.addTag(JTagsPanel.java:157)
        at org.magic.gui.components.editor.JTagsPanel$1.lambda$actionPerformed$0(JTagsPanel.java:81)
        at java.desktop/javax.swing.JTextField.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.JTextField.postActionEvent(Unknown Source)
        at java.desktop/javax.swing.JTextField$NotifyAction.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.SwingUtilities.notifyAction(Unknown Source)
        at java.desktop/javax.swing.JComponent.processKeyBinding(Unknown Source)
```

After failing adding tag, I can no more try to add tag, the button stay gray and unclickable : 

![image](https://user-images.githubusercontent.com/14327288/130570829-1278a79e-43ad-47a5-a924-1eee0364c69e.png)

**Comment by nicho92** [comment]
Hi, can you send me your log file ?

I need more information about your configuration (Look and feel and Jvm)

Thanks

**Comment by JulienSambre** [comment]
Hi!

Here it is : 

[mtgcompanion.log](https://github.com/nicho92/MtgDesktopCompanion/files/7037112/mtgcompanion.log)

**Comment by nicho92** [comment]
Did you import it ? or a handed created one ?

**Comment by JulienSambre** [comment]
I imported all my decks created with cockatrice.

**Comment by nicho92** [comment]
OK . I see the bug.. will be fixed in next release. in ScriptPanel, can you execute this script? : 
   `dao.executeQuery('update decks set tags = NULL where tags =""');`

then reopen your deck

**Comment by JulienSambre** [comment]
You are far too quick to respond :D.

The script fixed the problem.

Thanks!
