### ISSUE TITLE
Decklist won't fully load 'Cannot invoke "String.length()" because "s" is null'

### ISSUE THREAD

**Issue by Ads20000** [nicho92/MtgDesktopCompanion#181]
MTG Companion v2.26

I entered the Land's Wrath deck list (and added the cards in it to Stock and then Library) but after closing and reopening MTG Companion (and my computer) it won't load. The 'Open deck' dialogue box's loading circle gets stuck when trying to load it. The error is as follows:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
```
<details>
<summary>Rest of error message</summary>
	at net.coderazzi.filters.gui.editor.ChoicesListModel.addContent(ChoicesListModel.java:162) <br>
	at net.coderazzi.filters.gui.editor.PopupComponent.addChoices(PopupComponent.java:123) <br>
	at net.coderazzi.filters.gui.editor.FilterEditor.addChoices(FilterEditor.java:418) <br>
	at net.coderazzi.filters.gui.editor.FilterEditor.setChoices(FilterEditor.java:408) <br>
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport$EditorHandle.iterationCompleted(AdaptiveChoicesHandler.java:650) <br>
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.extractChoices(AdaptiveChoicesHandler.java:444) <br>
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.rowsAdded(AdaptiveChoicesHandler.java:269) <br>
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.tableChanged(AdaptiveChoicesHandler.java:243) <br>
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler.tableUpdated(AdaptiveChoicesHandler.java:137) <br>
	at net.coderazzi.filters.gui.ChoicesHandler.tableChanged(ChoicesHandler.java:108) <br>
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302) <br>
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableDataChanged(AbstractTableModel.java:204) <br>
	at org.magic.gui.abstracts.GenericTableModel.addItems(GenericTableModel.java:136) <br>
	at org.magic.gui.components.dialog.JDeckChooserDialog$2.process(JDeckChooserDialog.java:150) <br>
	at java.desktop/javax.swing.SwingWorker$3.run(SwingWorker.java:423) <br>
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) <br>
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847) <br>
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) <br>
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857) <br>
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310) <br>
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242) <br>
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316) <br>
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) <br>
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) <br>
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) <br>
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391) <br>
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) <br>
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) <br>
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) <br>
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) <br>
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) <br>
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312) <br>
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) <br>
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079) <br>
	at java.desktop/java.awt.Component.show(Component.java:1720) <br>
	at java.desktop/java.awt.Component.setVisible(Component.java:1667) <br>
	at java.desktop/java.awt.Window.setVisible(Window.java:1032) <br>
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1014) <br>
	at org.magic.gui.components.ConstructPanel.lambda$initGUI$2(ConstructPanel.java:369) <br>
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) <br>
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) <br>
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) <br>
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) <br>
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) <br>
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298) <br>
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617) <br>
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342) <br>
	at java.desktop/java.awt.Component.processEvent(Component.java:6382) <br>
	at java.desktop/java.awt.Container.processEvent(Container.java:2264) <br>
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993) <br>
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322) <br>
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825) <br>
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934) <br>
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563) <br>
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504) <br>
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308) <br>
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773) <br>
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825) <br>
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) <br>
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) <br>
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) <br>
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391) <br>
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) <br>
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) <br>
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745) <br>
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743) <br>
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391) <br>
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) <br>
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) <br>
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</details>

[mtgcompanion.log](https://github.com/nicho92/MtgDesktopCompanion/files/7073137/mtgcompanion.log)

**Comment by nicho92** [comment]
I tried to import it with success... did you saved it ? 
can you tried to import it from this Json file ? 

[Land_s_Wrath.json.txt](https://github.com/nicho92/MtgDesktopCompanion/files/7073241/Land_s_Wrath.json.txt)

**Comment by Ads20000** [comment]
Pretty sure it's a bug (or a database corruption or something? But pretty sure that's happened due to a bug...?) because now even less decks are loading, same error as previously.

![Screenshot from 2021-08-29 23-36-44](https://user-images.githubusercontent.com/3178485/131408431-b79c3fc8-71ab-4843-8745-5e6a991e3ce9.png)

**Comment by Ads20000** [comment]
Tried importing your JSON file and it imports successfully then again fails to load, either running into the '"s" is null' error after listing Mono-Green Stompy or Sneak Attack.

**Comment by nicho92** [comment]
is it possible for you to send me a export of your "decks" table ? do you use SQLIte DAO ?

**Comment by nicho92** [comment]
or in other way, your %USER_HOME%/.magicDeskCompanion/data/sqlite-db file

**Comment by Ads20000** [comment]
[sqlite-db](https://drive.google.com/file/d/1dtHXJbFFtxGkZI7wlXDJaIFdkSZYxgeq/view?usp=sharing)

**Comment by Ads20000** [comment]
No luck I'm afraid:
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null`

<details>
<summary>Rest of error message</summary>
	at net.coderazzi.filters.gui.editor.ChoicesListModel.addContent(ChoicesListModel.java:162) <br>
	at net.coderazzi.filters.gui.editor.PopupComponent.addChoices(PopupComponent.java:123) <br>
	at net.coderazzi.filters.gui.editor.FilterEditor.addChoices(FilterEditor.java:418) <br>
	at net.coderazzi.filters.gui.editor.FilterEditor.setChoices(FilterEditor.java:408) <br>
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport$EditorHandle.iterationCompleted(AdaptiveChoicesHandler.java:650) <br>
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.extractChoices(AdaptiveChoicesHandler.java:444) <br>
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.rowsAdded(AdaptiveChoicesHandler.java:269) <br>
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.tableChanged(AdaptiveChoicesHandler.java:243) <br>
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler.tableUpdated(AdaptiveChoicesHandler.java:137) <br>
	at net.coderazzi.filters.gui.ChoicesHandler.tableChanged(ChoicesHandler.java:108) <br>
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302) <br>
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableDataChanged(AbstractTableModel.java:204) <br>
	at org.magic.gui.abstracts.GenericTableModel.addItems(GenericTableModel.java:136) <br>
	at org.magic.gui.components.dialog.JDeckChooserDialog$2.process(JDeckChooserDialog.java:150) <br>
	at java.desktop/javax.swing.SwingWorker$3.run(SwingWorker.java:423) <br>
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) <br>
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847) <br>
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) <br>
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857) <br>
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310) <br>
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242) <br>
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316) <br>
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) <br>
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) <br>
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) <br>
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391) <br>
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) <br>
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) <br>
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) <br>
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) <br>
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) <br>
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312) <br>
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) <br>
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079) <br>
	at java.desktop/java.awt.Component.show(Component.java:1720) <br>
	at java.desktop/java.awt.Component.setVisible(Component.java:1667) <br>
	at java.desktop/java.awt.Window.setVisible(Window.java:1032) <br>
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1014) <br>
	at org.magic.gui.components.ConstructPanel.lambda$initGUI$2(ConstructPanel.java:369) <br>
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) <br>
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) <br>
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) <br>
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) <br>
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) <br>
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298) <br>
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617) <br>
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342) <br>
	at java.desktop/java.awt.Component.processEvent(Component.java:6382) <br>
	at java.desktop/java.awt.Container.processEvent(Container.java:2264) <br>
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993) <br>
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322) <br>
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825) <br>
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934) <br>
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563) <br>
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504) <br>
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308) <br>
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773) <br>
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825) <br>
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) <br>
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) <br>
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) <br>
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391) <br>
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) <br>
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) <br>
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745) <br>
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743) <br>
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391) <br>
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) <br>
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) <br>
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) <br>
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</details>

**Comment by nicho92** [comment]
Ooops .. My bad ... the query was wrong : 

dao.executeQuery("UPDATE decks set name='NO NAME' where name IS null");

**Comment by Ads20000** [comment]
That worked, thank you! :D

**Comment by Ads20000** [comment]
Fixed by editing `~/.magicDeskCompanion/data/sqlite-db` with [sqlitebrowser](https://snapcraft.io/sqlitebrowser) thanks for the recommendation @nicho92 !!
