### ISSUE TITLE
Can't start 2.36 MTGLogger NullPointerException

### ISSUE THREAD

**Issue by shithead** [nicho92/MtgDesktopCompanion#235]
**Configuration **
 - OS: nixos-22.05
 - Version 2.36

**Describe the bug**
On start  I get this message:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.magic.services.logging.MTGAppender.addObserver(org.utils.patterns.observer.Observer)" because the return value of "org.magic.services.logging.MTGLogger.getMTGAppender()" is null
	at org.magic.api.main.MtgDesktopCompanion.<init>(MtgDesktopCompanion.java:41)
	at org.magic.api.main.MtgDesktopCompanion.main(MtgDesktopCompanion.java:34)
```

**Comment by shithead** [comment]
I run the ZIP file in release doenloads. Selfbuild from git master works.

**Comment by nicho92** [comment]
can you send me the log4j2.xml file present in /lib/magic-api-2.36.jar  ? can you confirm that /lib/magic-api-2.35.jar is not present anymore ?

**Comment by shithead** [comment]
[log4j2.xml.txt](https://github.com/nicho92/MtgDesktopCompanion/files/9643843/log4j2.xml.txt)

remove txt to get pack the xml.

I think I have removed all magic-api-2.35.jar on my pc.

**Comment by nicho92** [comment]
can you try to remove all your previous setup file, unzip a fresh one, and run it ?

**Comment by shithead** [comment]
okay i have it, i search for all old jar files and remove it from my .local/lib and the it run.
