### ISSUE TITLE
Card won't add to stock

### ISSUE THREAD

**Issue by bewarellamas** [nicho92/MtgDesktopCompanion#298]
**Configuration **

OS: [e.g. iOS] : All
Version [e.g. 22] : 2.51
Provider : Scryfall Provider
DAO : All

Getting the attached error log when trying to add "Bushi Tenderfoot // Kenzo the Hardhearted" to stock from the search panel. Only shows error in the log and it appears to work until refreshing the view. Could be affecting more cards, but this is the one I noticed it with.

******Output log*****
2024-11-24 18:14:02 [DEBUG] org.magic.api.providers.impl.ScryFallProvider 193 - getting url https://api.scryfall.com/cards/search?q=%2B%2Bbushi+tend+include%3Aextras
2024-11-24 18:14:02 [DEBUG] org.magic.services.network.MTGHttpClient 107 - execute GET https://api.scryfall.com/cards/search?q=%2B%2Bbushi+tend+include%3Aextras HTTP/1.1
2024-11-24 18:14:02 [TRACE] org.magic.api.providers.impl.ScryFallProvider 440 - loyalty not found
2024-11-24 18:14:02 [TRACE] org.magic.api.providers.impl.ScryFallProvider 445 - watermark not found
2024-11-24 18:14:02 [ERROR] org.magic.api.providers.impl.ScryFallProvider 560 - Bushi Tenderfoot // Kenzo the Hardhearted has no loyalty: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsInt()" because the return value of "com.google.gson.JsonObject.get(String)" is null
2024-11-24 18:14:02 [ERROR] org.magic.api.providers.impl.ScryFallProvider 569 - Bushi Tenderfoot // Kenzo the Hardhearted has no colors: 
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonArray()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at org.magic.api.providers.impl.ScryFallProvider.generateCard(ScryFallProvider.java:565) ~[classes/:?]
	at org.magic.api.providers.impl.ScryFallProvider$1.call(ScryFallProvider.java:312) ~[classes/:?]
	at org.magic.api.providers.impl.ScryFallProvider$1.call(ScryFallProvider.java:1) ~[classes/:?]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4903) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3574) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2316) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4017) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4898) ~[guava-33.2.1-jre.jar:?]
	at org.magic.services.tools.TCache.get(TCache.java:60) ~[classes/:?]
	at org.magic.api.providers.impl.ScryFallProvider.loadCard(ScryFallProvider.java:308) ~[classes/:?]
	at org.magic.api.providers.impl.ScryFallProvider.searchCardByCriteria(ScryFallProvider.java:204) ~[classes/:?]
	at org.magic.gui.components.card.CardSearchPanel$4.doInBackground(CardSearchPanel.java:508) ~[classes/:?]
	at org.magic.gui.components.card.CardSearchPanel$4.doInBackground(CardSearchPanel.java:1) ~[classes/:?]
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:305) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:342) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-11-24 18:14:02 [DEBUG] org.magic.services.network.MTGHttpClient 107 - execute GET https://api.scryfall.com/cards/search?q=+%2B%2B%21%22Bushi+Tenderfoot+%2F%2F+Kenzo+the+Hardhearted%22%20include:extras%20-s:chk HTTP/1.1
2024-11-24 18:14:02 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:02 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT DISTINCT(collection) FROM stocks WHERE qte > 0 AND idmc='864ad989-19a6-4930-8efc-bbc077a18c32' and idMe='chk'
2024-11-24 18:14:02 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT * FROM alerts
2024-11-24 18:14:02 [TRACE] org.magic.api.pictures.impl.ScryFallPicturesProvider 57 - cached Bushi Tenderfoot // Kenzo the Hardhearted (Champions of Kamigawa) found
2024-11-24 18:14:02 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:02 [DEBUG] org.magic.gui.components.card.CardSearchPanel 739 - results 1 cards
2024-11-24 18:14:02 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:02 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT * FROM alerts
2024-11-24 18:14:02 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT DISTINCT(collection) FROM stocks WHERE qte > 0 AND idmc='864ad989-19a6-4930-8efc-bbc077a18c32' and idMe='chk'
2024-11-24 18:14:02 [TRACE] org.magic.api.pictures.impl.ScryFallPicturesProvider 57 - cached Bushi Tenderfoot // Kenzo the Hardhearted (Champions of Kamigawa) found
2024-11-24 18:14:02 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:02 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:02 [TRACE] org.magic.api.pictures.impl.ScryFallPicturesProvider 57 - cached Bushi Tenderfoot // Kenzo the Hardhearted (Champions of Kamigawa) found
2024-11-24 18:14:02 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:03 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:03 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT DISTINCT(collection) FROM stocks WHERE qte > 0 AND idmc='864ad989-19a6-4930-8efc-bbc077a18c32' and idMe='chk'
2024-11-24 18:14:03 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT * FROM alerts
2024-11-24 18:14:03 [TRACE] org.magic.api.pictures.impl.ScryFallPicturesProvider 57 - cached Bushi Tenderfoot // Kenzo the Hardhearted (Champions of Kamigawa) found
2024-11-24 18:14:03 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:04 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT * FROM stocks where idmc='864ad989-19a6-4930-8efc-bbc077a18c32'
2024-11-24 18:14:04 [TRACE] org.magic.api.dao.impl.MysqlDAO 1484 - loading 0 items FROM stock for Bushi Tenderfoot // Kenzo the Hardhearted
2024-11-24 18:14:08 [DEBUG] org.magic.api.dao.impl.MysqlDAO 1593 - save stock -1
2024-11-24 18:14:08 [ERROR] org.magic.api.dao.impl.MysqlDAO 1615 - com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1
2024-11-24 18:14:23 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:23 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT DISTINCT(collection) FROM stocks WHERE qte > 0 AND idmc='864ad989-19a6-4930-8efc-bbc077a18c32' and idMe='chk'
2024-11-24 18:14:23 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT * FROM alerts
2024-11-24 18:14:23 [TRACE] org.magic.api.pictures.impl.ScryFallPicturesProvider 57 - cached Bushi Tenderfoot // Kenzo the Hardhearted (Champions of Kamigawa) found
2024-11-24 18:14:23 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:23 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT * FROM stocks where idmc='864ad989-19a6-4930-8efc-bbc077a18c32'
2024-11-24 18:14:23 [TRACE] org.magic.api.dao.impl.MysqlDAO 1484 - loading 0 items FROM stock for Bushi Tenderfoot // Kenzo the Hardhearted
2024-11-24 18:14:25 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:25 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT DISTINCT(collection) FROM stocks WHERE qte > 0 AND idmc='864ad989-19a6-4930-8efc-bbc077a18c32' and idMe='chk'
2024-11-24 18:14:25 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT * FROM alerts
2024-11-24 18:14:25 [TRACE] org.magic.api.pictures.impl.ScryFallPicturesProvider 57 - cached Bushi Tenderfoot // Kenzo the Hardhearted (Champions of Kamigawa) found
2024-11-24 18:14:25 [TRACE] org.magic.api.cache.impl.FileCache 41 - search in cache : Bushi Tenderfoot // Kenzo the Hardhearted Champions of Kamigawa
2024-11-24 18:14:25 [TRACE] org.magic.api.dao.impl.MysqlDAO 1880 - Executing DAO Audit : SELECT * FROM stocks where idmc='864ad989-19a6-4930-8efc-bbc077a18c32'
2024-11-24 18:14:25 [TRACE] org.magic.api.dao.impl.MysqlDAO 1484 - loading 0 items FROM stock for Bushi Tenderfoot // Kenzo the Hardhearted

**Comment by bewarellamas** [comment]
Just had it happen with "Student of Elements // Tobita, Master of Winds" as well.

**Comment by nicho92** [comment]
OK i see ... Scryfall Provider need to be deeply updated... To wait, i suggest to use [SQLite ](https://github.com/nicho92/MtgDesktopCompanion/wiki/PROVIDER-MTGSQLive)
