### ISSUE TITLE
How can I run it on OSX?

### ISSUE THREAD

**Issue by Raystorm7** [nicho92/MtgDesktopCompanion#56]
Hi,

I would like to use this software but i don't know how to run it on OSX.

Can anyone help me please?

Thank you :)

**Comment by nicho92** [comment]
Hi, 

i'm sorry , i'm not a OSX user... but all you need is [java](https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html) installed on your OS. 
i think you can launch mtg-desktop-companion.sh to execute the app

**Comment by Raystorm7** [comment]
> Hi,
> 
> i'm sorry , i'm not a OSX user... but all you need is [java](https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html) installed on your OS.
> i think you can launch mtg-desktop-companion.sh to execute the app

Thank you!
I have tried to start it but this error occurs:

Unrecognized VM option '+UseStringDeduplication'
Could not create the Java virtual machine.

Also I have tried to start it in a Windows virtual machine but this error occurs:

![Error](https://i.imgur.com/VW7Yp4H.png)

**Comment by nicho92** [comment]
you can remove it with a text editor at line 120 : 

change 
`exec "$JAVACMD" $JAVA_OPTS -XX:+UseStringDeduplication -XX:+UseG1GC -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2" \
`
by

`exec "$JAVACMD" $JAVA_OPTS -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2" \`

**Comment by Raystorm7** [comment]
Thank you but now this error occurs:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/magic/api/main/MtgDesktopCompanion : Unsupported major.minor version 54.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

**Comment by Raystorm7** [comment]
I have to update to the latest version:
Java SE Development Kit 12

and now works!

Thank you! 👍

**Comment by nicho92** [comment]
can you send me file log files in /%user%/.magicDeskCompanion/logs

**Comment by Raystorm7** [comment]
[Here](https://ufile.io/vtjol) it is.

Thank you.

**Comment by nicho92** [comment]
too bad... the file is empty :/
i'm really a newbie on OSX. do you have a command prompt with some log or something else ?

**Comment by Raystorm7** [comment]
Here the [log](https://mega.nz/#!R5kEgY5S!OGphvlYmTQfXqTsrAHfRippYlPanM7J6EK6S4rMWZuo).

**Comment by nicho92** [comment]
ok, i see : there is an error with JXSearchField component with OSX  : 
java.lang.IllegalArgumentException: cannot add to layout: unknown constraint: LEFT

i'm looking on similar error on internet. i keep the ticket open.

Can you tell me your OSX version ?

**Comment by Raystorm7** [comment]
HI,
OSX 10.14.4 (18E226)
MacBook Pro (15-inch, 2018)

Thank you.

**Comment by nicho92** [comment]
can you try last version [2.4 ](https://github.com/nicho92/MtgDesktopCompanion/releases/tag/2.4)?

**Comment by Raystorm7** [comment]
Thank you, now it works!
[imgur](https://imgur.com/RgaA5lL)

The new logo is awesome! :D

The web version throw this error:
2019-04-14 07:35:32 ERROR org.magic.servers.impl.WebManagerServer 63  - couldn't write js rest file jar:file:/Users/pozzy/Downloads/mtg-desktop-companion-2.4/lib/magic-api-2.4.jar!/web-ui/dist/js/rest-server.js
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:418)
	at org.magic.servers.impl.WebManagerServer.start(WebManagerServer.java:61)
	at org.magic.api.main.WebUIServerLauncher.main(WebUIServerLauncher.java:19)

**Comment by nicho92** [comment]
ok Good News ! 

bugfix in 56e21da4e8985e78e33bf0ce0ff98f29bfe07b50

i'm creating a new issue for website server
