### ISSUE TITLE
webserver startup error

### ISSUE THREAD

**Issue by nicho92** [nicho92/MtgDesktopCompanion#57]
The web version throw this error:
2019-04-14 07:35:32 ERROR org.magic.servers.impl.WebManagerServer 63 - couldn't write js rest file jar:file:/Users/pozzy/Downloads/mtg-desktop-companion-2.4/lib/magic-api-2.4.jar!/web-ui/dist/js/rest-server.js
java.lang.IllegalArgumentException: URI is not hierarchical
at java.base/java.io.File.(File.java:418)
at org.magic.servers.impl.WebManagerServer.start(WebManagerServer.java:61)
at org.magic.api.main.WebUIServerLauncher.main(WebUIServerLauncher.java:19)

**Comment by nicho92** [comment]
bugfixed in cbea0c95c29080c392250042767ad99ff2a0e08e

**Comment by nicho92** [comment]
it's bugfixed , and i re-upload a new 2.4 version [here](https://github.com/nicho92/MtgDesktopCompanion/releases/tag/2.4)
You can download it again.
Thanks

**Comment by Raystorm7** [comment]
WOW!
Nice work!

Thank you!

**Comment by nicho92** [comment]
you're welcome.

Thanks for your feedback on osx ;)
